var produtos = [
    {
        id: 1,
        nome: 'Tropical 300ML',
        category: 'Copo',
        descricao: 'Kiwi, Banana, Abacaxi, Leite Condesado',
        ml: '300ml',
        img: 'img/tropical.jpg',
        price: 19,
        quantity: 1,
    },
    {
        id: 2,
        nome: 'Sensação 300ML',
        category: 'Copo',
        descricao: 'Nutella, Morango, Leite Condesado',
        ml: '300ml',
        img: 'img/sensação .jpg',
        price: 20,
        quantity: 1,
    },
    {
        id: 3,
        nome: 'Tradicional 300ML',
        category: 'Copo',
        descricao: 'Banana, Morango, Granola, Leite em Pó, Leite Condesado',
        ml: '300ml',
        img: 'img/tradicional .jpg',
        price: 20,
        quantity: 1,
    },
    {
        id: 4,
        nome: 'Ninhotella 300ML',
        category: 'Copo',
        descricao: 'Nutella, Creme Ninho, Ovomaltine',
        ml: '300ml',
        img: 'img/ninhotella.jpg',
        price: 20,
        quantity: 1,
    },
    {
        id: 5,
        nome: 'Paçokita 300ML',
        category: 'Copo',
        descricao: 'Creme Ninho, Paçoca, Amendoim Triturado',
        ml: '300ml',
        img: 'img/paçokita.jpg',
        price: 19,
        quantity: 1,
    },
    {
        id: 6,
        img: 'img/copo da sara.jpg',
        nome: 'Açai da Sara 300ML',
        descricao: 'Nutella, Morango, Ovomaltine, Brigadeiro',
        category: 'Copo',
        ml: '300ml',
        price: 24,
        quantity: 1,
    },
    {
        id: 43,
        nome: 'Tropical 500ML',
        category: 'Copo500ml',
        descricao: 'Kiwi, Banana, Abacaxi, Leite Condesado',
        ml: '500ml',
        img: 'img/tropical.jpg',
        price: 21,
        quantity: 1,
    },
    {
        id: 44,
        nome: 'Sensação 500ML',
        category: 'Copo500ml',
        descricao: 'Nutella, Morango, Leite Condesado',
        ml: '500ml',
        img: 'img/sensação .jpg',
        price: 22,
        quantity: 1,
    },
    {
        id: 45,
        nome: 'Tradicional 500ML',
        category: 'Copo500ml',
        descricao: 'Banana, Morango, Granola, Leite em Pó, Leite Condesado',
        ml: '500ml',
        img: 'img/tradicional .jpg',
        price: 22,
        quantity: 1,
    },
    {
        id: 46,
        nome: 'Ninhotella 500ML',
        category: 'Copo500ml',
        descricao: 'Nutella, Creme Ninho, Ovomaltine',
        ml: '500ml',
        img: 'img/ninhotella.jpg',
        price: 22,
        quantity: 1,
    },
    {
        id: 47,
        nome: 'Paçokita 500ML',
        category: 'Copo500ml',
        descricao: 'Creme Ninho, Paçoca, Amendoim Triturado',
        ml: '500ml',
        img: 'img/paçokita.jpg',
        price: 21,
        quantity: 1,
    },
    {
        id: 48,
        img: 'img/copo da sara.jpg',
        nome: 'Açai da Sara 500ML',
        descricao: 'Nutella, Morango, Ovomaltine, Brigadeiro',
        category: 'Copo500ml',
        ml: '500ml',
        price: 26,
        quantity: 1,
    },
    {
        id: 49,
        nome: 'Tropical 700ML',
        category: 'Copo700ml',
        descricao: 'Kiwi, Banana, Abacaxi, Leite Condesado',
        ml: '700ml',
        img: 'img/tropical.jpg',
        price: 23,
        quantity: 1,
    },
    {
        id: 50,
        nome: 'Sensação 700ML',
        category: 'Copo700ml',
        descricao: 'Nutella, Morango, Leite Condesado',
        ml: '700ml',
        img: 'img/sensação .jpg',
        price: 24,
        quantity: 1,
    },
    {
        id: 51,
        nome: 'Tradicional 700ML',
        category: 'Copo700ml',
        descricao: 'Banana, Morango, Granola, Leite em Pó, Leite Condesado',
        ml: '700ml',
        img: 'img/tradicional .jpg',
        price: 24,
        quantity: 1,
    },
    {
        id: 52,
        nome: 'Ninhotella 700ML',
        category: 'Copo700ml',
        descricao: 'Nutella, Creme Ninho, Ovomaltine',
        ml: '700ml',
        img: 'img/ninhotella.jpg',
        price: 24,
        quantity: 1,
    },
    {
        id: 53,
        nome: 'Paçokita 700ML',
        category: 'Copo700ml',
        descricao: 'Creme Ninho, Paçoca, Amendoim Triturado',
        ml: '700ml',
        img: 'img/paçokita.jpg',
        price: 23,
        quantity: 1,
    },
    {
        id: 54,
        img: 'img/copo da sara.jpg',
        nome: 'Açai da Sara 700ML',
        descricao: 'Nutella, Morango, Ovomaltine, Brigadeiro',
        category: 'Copo700ml',
        ml: '700ml',
        price: 28,
        quantity: 1,
    },
    {
        id: 8,
        nome: 'Roleta de açaí',
        descricao: 'Roleta +5 adicionais (Adicionais escolher no whattsap)',
        img: 'img/roleta.jpg',
        category: 'Especial',
        ml: '1L',
        quantity: 1,
        price: 40
    },
    {
        id: 9,
        nome: 'Abacaxi',
        descricao: 'FRUTA',
        img: 'img/abacaxi.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 65,
        nome: 'Uva',
        descricao: 'FRUTA',
        img: 'img/uva.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 10,
        nome: 'Banana',
        descricao: 'FRUTA',
        img: 'img/banana .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 2
    },
    {
        id: 11,
        nome: 'Manga',
        descricao: 'FRUTA',
        img: 'img/manga.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 12,
        nome: 'Morango',
        descricao: 'FRUTA',
        img: 'img/morango.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 13,
        nome: 'Kiwi',
        descricao: 'FRUTA',
        img: 'img/kiwi.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 14,
        nome: 'Nutella',
        descricao: 'CHOCOLATE',
        img: 'img/Nutella-original.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 5
    },
    {
        id: 15,
        nome: 'Creme de Avelã',
        descricao: 'CHOCOLATE',
        img: 'img/creme-de-avela.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 16,
        nome: 'Brigadeiro',
        descricao: 'CHOCOLATE',
        img: 'img/brigadeiro .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 17,
        nome: 'Kinder Bueno',
        descricao: 'CHOCOLATE',
        img: 'img/Kinder Bueno .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 4
    },
    {
        id: 18,
        nome: 'Confete',
        descricao: 'CHOCOLATE',
        img: 'img/M & M .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 19,
        nome: 'Creme de Ninho',
        descricao: 'CHOCOLATE',
        img: 'img/creme-de-ninho.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 4
    },
    {
        id: 22,
        nome: 'Creme de Diamante Negro',
        descricao: 'CHOCOLATE',
        img: 'img/creme de diamante negro.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 5
    },
    {
        id: 25,
        nome: 'Kit Kat',
        descricao: 'CHOCOLATE',
        img: 'img/kitkat.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 26,
        nome: 'Diamante Negro',
        descricao: 'CHOCOLATE',
        img: 'img/diamante negro.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 27,
        nome: 'Laka',
        descricao: 'CHOCOLATE',
        img: 'img/laka.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 28,
        nome: 'Laka Oreo',
        descricao: 'CHOCOLATE',
        img: 'img/laka oreo.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 29,
        nome: 'Suflair',
        descricao: 'CHOCOLATE',
        img: 'img/suflair.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 30,
        nome: 'Bis Branco',
        descricao: 'CHOCOLATE',
        img: 'img/bis branco.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 31,
        nome: 'Bis Preto',
        descricao: 'CHOCOLATE',
        img: 'img/bis preto.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 32,
        nome: 'Ouro Branco',
        descricao: 'CHOCOLATE',
        img: 'img/ouro branco .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 33,
        nome: 'Sonho de Valsa',
        descricao: 'CHOCOLATE',
        img: 'img/sonho de valsa .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 34,
        nome: 'Doce de Leite',
        descricao: 'CHOCOLATE',
        img: 'img/creme de leite .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 2
    },
    {
        id: 35,
        nome: 'Sucrilhos',
        descricao: 'CHOCOLATE',
        img: 'img/sucrilhos.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 2
    },
    {
        id: 36,
        nome: 'iogurte',
        descricao: 'CHOCOLATE',
        img: 'img/iogurte .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 2
    },
    {
        id: 37,
        nome: 'Granola',
        descricao: 'CHOCOLATE',
        img: 'img/granola.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 2
    },
    {
        id: 38,
        nome: 'Leite em pó',
        descricao: 'CHOCOLATE',
        img: 'img/leite em pó .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 39,
        nome: 'Leite Condensado',
        descricao: 'CHOCOLATE',
        img: 'img/leite condensado .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 40,
        nome: 'Ovomaltine',
        descricao: 'CHOCOLATE',
        img: 'img/ovomaltine .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 41,
        nome: 'Paçoca',
        descricao: 'CHOCOLATE',
        img: 'img/paçoca .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 2
    },
    {
        id: 42,
        nome: 'amendoim Triturado',
        descricao: 'CHOCOLATE',
        img: 'img/Amendoim .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    }, 
    {
        id: 55,
        nome: 'Copo 300ML',
        category: 'Montar Copo',
        descricao: 'Monte um copo de cada vez',
        price: 10,
        img: 'img/copo300.jpg',
        quantity: 1

    },
    {
        id: 56,
        nome: 'Copo 500ML',
        category: 'Montar Copo',
        descricao: 'Monte um copo de cada vez',
        price: 12,
        img: 'img/copo500.jpg',
        quantity: 1
    },
    {
        id: 57,
        nome: 'Copo 700ML',
        category: 'Montar Copo',
        descricao: 'Monte um copo de cada vez',
        price: 14,
        img: 'img/copo700.jpg',
        quantity: 1
    },
    {
        id: 58,
        nome: 'Copo 1L',
        category: 'Montar Copo',
        descricao: 'Monte um copo de cada vez',
        price: 23,
        img: 'img/copo só de açaí .jpg',
        quantity: 1
    },
    {
        id: 59,
        nome: 'Kids 300ML',
        category: 'Copo',
        descricao: 'leite condensado, leite em pó, confete',
        price: 18,
        img: 'img/copo de açaí .jpg',
        quantity: 1
    },
    {
        id: 60,
        nome: 'Kids 500ML',
        category: 'Copo500ml',
        descricao: 'leite condensado, leite em pó, confete',
        price: 20,
        img: 'img/copo de açaí .jpg',
        quantity: 1
    },
    {
        id: 61,
        nome: 'Kids 700ML',
        category: 'Copo700ml',
        descricao: 'leite condensado, leite em pó, confete',
        price: 22,
        img: 'img/copo de açaí .jpg',
        quantity: 1
    },
    {
        id: 62,
        nome: 'Trufado 300ML',
        category: 'Copo',
        descricao: 'leite condensado, nutella, morango, kinder bueno',
        price: 23,
        img: 'img/trufado.jpg',
        quantity: 1
    },
    {
        id: 63,
        nome: 'Trufado 500ML',
        category: 'Copo500ml',
        descricao: 'leite condensado, nutella, morango, kinder bueno',
        price: 25,
        img: 'img/trufado.jpg',
        quantity: 1
    },
    {
        id: 64,
        nome: 'Trufado 700ML',
        category: 'Copo700ml',
        descricao: 'leite condensado, nutella, morango, kinder bueno',
        price: 27,
        img: 'img/trufado.jpg',
        quantity: 1
    },
    {
        id: 66,
        nome: 'Mel',
        descricao: 'Mel',
        img: 'img/mel.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 2
    },
    {
        id: 67,
        nome: 'Mousse de morango',
        descricao: 'Chocolate',
        img: 'img/mousse de morango.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 5
    },
    {
        id: 68,
        nome: 'Chocoboll',
        descricao: 'Chocolate',
        img: 'img/chocoball.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 4
    },
    {
        id: 69,
        nome: 'Marshmallow',
        descricao: 'Chocolate',
        img: 'img/marshmallow .jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 70,
        nome: 'Balas de goma',
        descricao: 'Chocolate',
        img: 'img/balas de goma.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 71,
        nome: 'Chocolate granulado',
        descricao: 'Chocolate',
        img: 'img/chocolate granulado.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 72,
        nome: 'Granulado colorido',
        descricao: 'Chocolate',
        img: 'img/granulado colorido.jpg',
        category: 'Adicionais',
        quantity: 1,
        price: 3
    },
    {
        id: 73,
        nome: 'Marmita de açaí',
        descricao: 'Contém somente 1l de açaí',
        img: 'img/marmita só de açaí .jpg',
        category: 'Especial',
        ml: '1L',
        quantity: 1,
        price: 23
    },

]

export { produtos };